language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
after_script:
- npm run coverage
deploy:
  provider: npm
  email: 285516193@qq.com
  api_key:
    secure: pzLkDm4Zgw92ZotPMqakv2JoX1iv7IpH7b78huz2cy51Uuin/fTuPxcnfv1aB37YFRhWjhQbAdvrQJBANy0QtNRvVJi0HWL++fjHu6CoB2C6WF5Y50M26Ge7F5DeqakKN9jArjQS0NllKpDWG7vfdUIBsl5f6SsIHmnRtCXPLak1jr4mzTaT7u7E4jk73RiBJXhintjQpc6LxoB2ZRay9EbcEM5RCsuVIIZfNN9YqQynunaKlpUnLOSmZJilanLL4vrV1kVgGg5bNROVvEhaRjIAyXh+lAOJeOBo7BGbdhkS60noVupOU4XxFUsDQxdD2etdQOdL7vOOqS/PYuoan1q0gx7zfc6e/kIj+jBwhPMTVTBA2jRJIrh6o+5r5/0q2uDRMHwXaVQQqTvHhK0mIZCL521+MsKc9npalcTjDaeXD+If6W1xjTzgLGF+0+XoEw/jcGTduFVNsTV6UiC982S6H5gsL9yfpunuBLrLFrwmnYPeLQMGNaZuQlTsZgc/P98TGSZCbrzETV8J594D/q1o/0iDMlvbmtLWII81sYb6RpYkLN23smRFri2+ymEOaGh2m/A0hXBXFDtturZK6Owl5aR8RFv0AGw7WGHOZJHNeIdA1lO5MHheLcMasJHTrlakSgPI5l+m44ycV/8Pb1si2ZbotSRbGqblBrFfHj0=
  skip_cleanup: true
  on:
    tags: true
    repo: yunkeCN/json-convert
git:
  depth: 3
